/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Professor } from "./Professor";
import { ProfessorCountArgs } from "./ProfessorCountArgs";
import { ProfessorFindManyArgs } from "./ProfessorFindManyArgs";
import { ProfessorFindUniqueArgs } from "./ProfessorFindUniqueArgs";
import { CreateProfessorArgs } from "./CreateProfessorArgs";
import { UpdateProfessorArgs } from "./UpdateProfessorArgs";
import { DeleteProfessorArgs } from "./DeleteProfessorArgs";
import { ProfessorAssignmentFindManyArgs } from "../../professorAssignment/base/ProfessorAssignmentFindManyArgs";
import { ProfessorAssignment } from "../../professorAssignment/base/ProfessorAssignment";
import { ScheduleFindManyArgs } from "../../schedule/base/ScheduleFindManyArgs";
import { Schedule } from "../../schedule/base/Schedule";
import { WeeklyProfessorAvailabilityFindManyArgs } from "../../weeklyProfessorAvailability/base/WeeklyProfessorAvailabilityFindManyArgs";
import { WeeklyProfessorAvailability } from "../../weeklyProfessorAvailability/base/WeeklyProfessorAvailability";
import { ProfessorService } from "../professor.service";
@graphql.Resolver(() => Professor)
export class ProfessorResolverBase {
  constructor(protected readonly service: ProfessorService) {}

  async _professorsMeta(
    @graphql.Args() args: ProfessorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Professor])
  async professors(
    @graphql.Args() args: ProfessorFindManyArgs
  ): Promise<Professor[]> {
    return this.service.professors(args);
  }

  @graphql.Query(() => Professor, { nullable: true })
  async professor(
    @graphql.Args() args: ProfessorFindUniqueArgs
  ): Promise<Professor | null> {
    const result = await this.service.professor(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Professor)
  async createProfessor(
    @graphql.Args() args: CreateProfessorArgs
  ): Promise<Professor> {
    return await this.service.createProfessor({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Professor)
  async updateProfessor(
    @graphql.Args() args: UpdateProfessorArgs
  ): Promise<Professor | null> {
    try {
      return await this.service.updateProfessor({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Professor)
  async deleteProfessor(
    @graphql.Args() args: DeleteProfessorArgs
  ): Promise<Professor | null> {
    try {
      return await this.service.deleteProfessor(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [ProfessorAssignment], {
    name: "professorAssignments",
  })
  async findProfessorAssignments(
    @graphql.Parent() parent: Professor,
    @graphql.Args() args: ProfessorAssignmentFindManyArgs
  ): Promise<ProfessorAssignment[]> {
    const results = await this.service.findProfessorAssignments(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Schedule], { name: "schedule" })
  async findSchedule(
    @graphql.Parent() parent: Professor,
    @graphql.Args() args: ScheduleFindManyArgs
  ): Promise<Schedule[]> {
    const results = await this.service.findSchedule(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [WeeklyProfessorAvailability], {
    name: "weeklyProfessorAvailability",
  })
  async findWeeklyProfessorAvailability(
    @graphql.Parent() parent: Professor,
    @graphql.Args() args: WeeklyProfessorAvailabilityFindManyArgs
  ): Promise<WeeklyProfessorAvailability[]> {
    const results = await this.service.findWeeklyProfessorAvailability(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }
}
