/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GroupOverlapService } from "../groupOverlap.service";
import { GroupOverlapCreateInput } from "./GroupOverlapCreateInput";
import { GroupOverlap } from "./GroupOverlap";
import { GroupOverlapFindManyArgs } from "./GroupOverlapFindManyArgs";
import { GroupOverlapWhereUniqueInput } from "./GroupOverlapWhereUniqueInput";
import { GroupOverlapUpdateInput } from "./GroupOverlapUpdateInput";

export class GroupOverlapControllerBase {
  constructor(protected readonly service: GroupOverlapService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GroupOverlap })
  async createGroupOverlap(
    @common.Body() data: GroupOverlapCreateInput
  ): Promise<GroupOverlap> {
    return await this.service.createGroupOverlap({
      data: {
        ...data,

        group1: {
          connect: data.group1,
        },

        group2: {
          connect: data.group2,
        },
      },
      select: {
        canOverlap: true,

        group1: {
          select: {
            id: true,
          },
        },

        group2: {
          select: {
            id: true,
          },
        },

        id: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [GroupOverlap] })
  @ApiNestedQuery(GroupOverlapFindManyArgs)
  async groupOverlaps(@common.Req() request: Request): Promise<GroupOverlap[]> {
    const args = plainToClass(GroupOverlapFindManyArgs, request.query);
    return this.service.groupOverlaps({
      ...args,
      select: {
        canOverlap: true,

        group1: {
          select: {
            id: true,
          },
        },

        group2: {
          select: {
            id: true,
          },
        },

        id: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GroupOverlap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async groupOverlap(
    @common.Param() params: GroupOverlapWhereUniqueInput
  ): Promise<GroupOverlap | null> {
    const result = await this.service.groupOverlap({
      where: params,
      select: {
        canOverlap: true,

        group1: {
          select: {
            id: true,
          },
        },

        group2: {
          select: {
            id: true,
          },
        },

        id: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GroupOverlap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateGroupOverlap(
    @common.Param() params: GroupOverlapWhereUniqueInput,
    @common.Body() data: GroupOverlapUpdateInput
  ): Promise<GroupOverlap | null> {
    try {
      return await this.service.updateGroupOverlap({
        where: params,
        data: {
          ...data,

          group1: {
            connect: data.group1,
          },

          group2: {
            connect: data.group2,
          },
        },
        select: {
          canOverlap: true,

          group1: {
            select: {
              id: true,
            },
          },

          group2: {
            select: {
              id: true,
            },
          },

          id: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GroupOverlap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteGroupOverlap(
    @common.Param() params: GroupOverlapWhereUniqueInput
  ): Promise<GroupOverlap | null> {
    try {
      return await this.service.deleteGroupOverlap({
        where: params,
        select: {
          canOverlap: true,

          group1: {
            select: {
              id: true,
            },
          },

          group2: {
            select: {
              id: true,
            },
          },

          id: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
