/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ExceptionalClosure } from "./ExceptionalClosure";
import { ExceptionalClosureCountArgs } from "./ExceptionalClosureCountArgs";
import { ExceptionalClosureFindManyArgs } from "./ExceptionalClosureFindManyArgs";
import { ExceptionalClosureFindUniqueArgs } from "./ExceptionalClosureFindUniqueArgs";
import { CreateExceptionalClosureArgs } from "./CreateExceptionalClosureArgs";
import { UpdateExceptionalClosureArgs } from "./UpdateExceptionalClosureArgs";
import { DeleteExceptionalClosureArgs } from "./DeleteExceptionalClosureArgs";
import { TimeSlot } from "../../timeSlot/base/TimeSlot";
import { AcademicWeek } from "../../academicWeek/base/AcademicWeek";
import { ExceptionalClosureService } from "../exceptionalClosure.service";
@graphql.Resolver(() => ExceptionalClosure)
export class ExceptionalClosureResolverBase {
  constructor(protected readonly service: ExceptionalClosureService) {}

  async _exceptionalClosuresMeta(
    @graphql.Args() args: ExceptionalClosureCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ExceptionalClosure])
  async exceptionalClosures(
    @graphql.Args() args: ExceptionalClosureFindManyArgs
  ): Promise<ExceptionalClosure[]> {
    return this.service.exceptionalClosures(args);
  }

  @graphql.Query(() => ExceptionalClosure, { nullable: true })
  async exceptionalClosure(
    @graphql.Args() args: ExceptionalClosureFindUniqueArgs
  ): Promise<ExceptionalClosure | null> {
    const result = await this.service.exceptionalClosure(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ExceptionalClosure)
  async createExceptionalClosure(
    @graphql.Args() args: CreateExceptionalClosureArgs
  ): Promise<ExceptionalClosure> {
    return await this.service.createExceptionalClosure({
      ...args,
      data: {
        ...args.data,

        timeSlot: {
          connect: args.data.timeSlot,
        },

        week: {
          connect: args.data.week,
        },
      },
    });
  }

  @graphql.Mutation(() => ExceptionalClosure)
  async updateExceptionalClosure(
    @graphql.Args() args: UpdateExceptionalClosureArgs
  ): Promise<ExceptionalClosure | null> {
    try {
      return await this.service.updateExceptionalClosure({
        ...args,
        data: {
          ...args.data,

          timeSlot: {
            connect: args.data.timeSlot,
          },

          week: {
            connect: args.data.week,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ExceptionalClosure)
  async deleteExceptionalClosure(
    @graphql.Args() args: DeleteExceptionalClosureArgs
  ): Promise<ExceptionalClosure | null> {
    try {
      return await this.service.deleteExceptionalClosure(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => TimeSlot, {
    nullable: true,
    name: "timeSlot",
  })
  async getTimeSlot(
    @graphql.Parent() parent: ExceptionalClosure
  ): Promise<TimeSlot | null> {
    const result = await this.service.getTimeSlot(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => AcademicWeek, {
    nullable: true,
    name: "week",
  })
  async getWeek(
    @graphql.Parent() parent: ExceptionalClosure
  ): Promise<AcademicWeek | null> {
    const result = await this.service.getWeek(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
