/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Schedule } from "./Schedule";
import { ScheduleCountArgs } from "./ScheduleCountArgs";
import { ScheduleFindManyArgs } from "./ScheduleFindManyArgs";
import { ScheduleFindUniqueArgs } from "./ScheduleFindUniqueArgs";
import { CreateScheduleArgs } from "./CreateScheduleArgs";
import { UpdateScheduleArgs } from "./UpdateScheduleArgs";
import { DeleteScheduleArgs } from "./DeleteScheduleArgs";
import { Course } from "../../course/base/Course";
import { Group } from "../../group/base/Group";
import { Professor } from "../../professor/base/Professor";
import { Room } from "../../room/base/Room";
import { TimeSlot } from "../../timeSlot/base/TimeSlot";
import { AcademicWeek } from "../../academicWeek/base/AcademicWeek";
import { ScheduleService } from "../schedule.service";
@graphql.Resolver(() => Schedule)
export class ScheduleResolverBase {
  constructor(protected readonly service: ScheduleService) {}

  async _schedulesMeta(
    @graphql.Args() args: ScheduleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Schedule])
  async schedules(
    @graphql.Args() args: ScheduleFindManyArgs
  ): Promise<Schedule[]> {
    return this.service.schedules(args);
  }

  @graphql.Query(() => Schedule, { nullable: true })
  async schedule(
    @graphql.Args() args: ScheduleFindUniqueArgs
  ): Promise<Schedule | null> {
    const result = await this.service.schedule(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Schedule)
  async createSchedule(
    @graphql.Args() args: CreateScheduleArgs
  ): Promise<Schedule> {
    return await this.service.createSchedule({
      ...args,
      data: {
        ...args.data,

        course: {
          connect: args.data.course,
        },

        group: {
          connect: args.data.group,
        },

        professor: {
          connect: args.data.professor,
        },

        room: {
          connect: args.data.room,
        },

        timeSlot: {
          connect: args.data.timeSlot,
        },

        week: {
          connect: args.data.week,
        },
      },
    });
  }

  @graphql.Mutation(() => Schedule)
  async updateSchedule(
    @graphql.Args() args: UpdateScheduleArgs
  ): Promise<Schedule | null> {
    try {
      return await this.service.updateSchedule({
        ...args,
        data: {
          ...args.data,

          course: {
            connect: args.data.course,
          },

          group: {
            connect: args.data.group,
          },

          professor: {
            connect: args.data.professor,
          },

          room: {
            connect: args.data.room,
          },

          timeSlot: {
            connect: args.data.timeSlot,
          },

          week: {
            connect: args.data.week,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Schedule)
  async deleteSchedule(
    @graphql.Args() args: DeleteScheduleArgs
  ): Promise<Schedule | null> {
    try {
      return await this.service.deleteSchedule(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Course, {
    nullable: true,
    name: "course",
  })
  async getCourse(@graphql.Parent() parent: Schedule): Promise<Course | null> {
    const result = await this.service.getCourse(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Group, {
    nullable: true,
    name: "group",
  })
  async getGroup(@graphql.Parent() parent: Schedule): Promise<Group | null> {
    const result = await this.service.getGroup(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Professor, {
    nullable: true,
    name: "professor",
  })
  async getProfessor(
    @graphql.Parent() parent: Schedule
  ): Promise<Professor | null> {
    const result = await this.service.getProfessor(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Room, {
    nullable: true,
    name: "room",
  })
  async getRoom(@graphql.Parent() parent: Schedule): Promise<Room | null> {
    const result = await this.service.getRoom(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => TimeSlot, {
    nullable: true,
    name: "timeSlot",
  })
  async getTimeSlot(
    @graphql.Parent() parent: Schedule
  ): Promise<TimeSlot | null> {
    const result = await this.service.getTimeSlot(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => AcademicWeek, {
    nullable: true,
    name: "week",
  })
  async getWeek(
    @graphql.Parent() parent: Schedule
  ): Promise<AcademicWeek | null> {
    const result = await this.service.getWeek(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
