/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ProfessorAssignment } from "./ProfessorAssignment";
import { ProfessorAssignmentCountArgs } from "./ProfessorAssignmentCountArgs";
import { ProfessorAssignmentFindManyArgs } from "./ProfessorAssignmentFindManyArgs";
import { ProfessorAssignmentFindUniqueArgs } from "./ProfessorAssignmentFindUniqueArgs";
import { CreateProfessorAssignmentArgs } from "./CreateProfessorAssignmentArgs";
import { UpdateProfessorAssignmentArgs } from "./UpdateProfessorAssignmentArgs";
import { DeleteProfessorAssignmentArgs } from "./DeleteProfessorAssignmentArgs";
import { Course } from "../../course/base/Course";
import { Group } from "../../group/base/Group";
import { Professor } from "../../professor/base/Professor";
import { ProfessorAssignmentService } from "../professorAssignment.service";
@graphql.Resolver(() => ProfessorAssignment)
export class ProfessorAssignmentResolverBase {
  constructor(protected readonly service: ProfessorAssignmentService) {}

  async _professorAssignmentsMeta(
    @graphql.Args() args: ProfessorAssignmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ProfessorAssignment])
  async professorAssignments(
    @graphql.Args() args: ProfessorAssignmentFindManyArgs
  ): Promise<ProfessorAssignment[]> {
    return this.service.professorAssignments(args);
  }

  @graphql.Query(() => ProfessorAssignment, { nullable: true })
  async professorAssignment(
    @graphql.Args() args: ProfessorAssignmentFindUniqueArgs
  ): Promise<ProfessorAssignment | null> {
    const result = await this.service.professorAssignment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ProfessorAssignment)
  async createProfessorAssignment(
    @graphql.Args() args: CreateProfessorAssignmentArgs
  ): Promise<ProfessorAssignment> {
    return await this.service.createProfessorAssignment({
      ...args,
      data: {
        ...args.data,

        course: {
          connect: args.data.course,
        },

        group: {
          connect: args.data.group,
        },

        professor: {
          connect: args.data.professor,
        },
      },
    });
  }

  @graphql.Mutation(() => ProfessorAssignment)
  async updateProfessorAssignment(
    @graphql.Args() args: UpdateProfessorAssignmentArgs
  ): Promise<ProfessorAssignment | null> {
    try {
      return await this.service.updateProfessorAssignment({
        ...args,
        data: {
          ...args.data,

          course: {
            connect: args.data.course,
          },

          group: {
            connect: args.data.group,
          },

          professor: {
            connect: args.data.professor,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ProfessorAssignment)
  async deleteProfessorAssignment(
    @graphql.Args() args: DeleteProfessorAssignmentArgs
  ): Promise<ProfessorAssignment | null> {
    try {
      return await this.service.deleteProfessorAssignment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Course, {
    nullable: true,
    name: "course",
  })
  async getCourse(
    @graphql.Parent() parent: ProfessorAssignment
  ): Promise<Course | null> {
    const result = await this.service.getCourse(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Group, {
    nullable: true,
    name: "group",
  })
  async getGroup(
    @graphql.Parent() parent: ProfessorAssignment
  ): Promise<Group | null> {
    const result = await this.service.getGroup(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Professor, {
    nullable: true,
    name: "professor",
  })
  async getProfessor(
    @graphql.Parent() parent: ProfessorAssignment
  ): Promise<Professor | null> {
    const result = await this.service.getProfessor(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
